version: "3.7"

services:
  tree-app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true        # for beautiful debug and pretty error output 
    environment:
      - NODE_ENV=development
      - REACT_APP_SERVER_ADDR=http://localhost:3333
    ports:
      - 8080:8080
